### ISSUE TITLE
Practica 1_ Validacion de propuesta de valor

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-tlax-room#2]
[PRACTICA 1_ PROPUESTA DE VALOR.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-tlax-room/files/6120753/PRACTICA.1_.PROPUESTA.DE.VALOR.pdf)

**Comment by ElvisS10** [comment]
El documento esta bien estructurado y conforme a lo que hemos hecho desde el inicio en nuestro repositorio y las modificaciones que se han realizado 👍

**Comment by josealfredo79** [comment]
Muy bien hecho...y revisado.
