### ISSUE TITLE
Práctica  de Costos

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-tlax-room#3]
[PRACTICA 2- COSTOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-tlax-room/files/6136181/PRACTICA.2-.COSTOS.pdf)

**Comment by ElvisS10** [comment]
Buen planteamiento sobre los costos para el desarrollo de su software 👍

**Comment by josealfredo79** [comment]
Bien hecho y revisado solo verificar el costo de alojamiento de servidor Web o en la Nube...
